version: "3.4"
services:
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db
  db:
    image: mariadb:10.3
    container_name: energyLiveDataDB
    restart: always
    volumes:
      - ./data_microservices/Shared/database/db.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: energylive
      MYSQL_PASSWORD: root
  frontend:
    build:
      dockerfile: Dockerfile
      context: "./frontend"
    container_name: frontend
    volumes:
      - './frontend/src:/app/src'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      CHOKIDAR_USEPOLLING: "true"
