version: '3'
services:
  zookeeper:
    ports:
      - '50000:2181'
    image: wurstmeister/zookeeper
  kafka:
    ports:
      - '9092:9092'
    expose:
      - "9093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9093, EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9093, EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CREATE_TOPICS: 'actual-generation-per-type:1:1,actual-total-load:1:1,physical-flow:1:1'
    image: 'wurstmeister/kafka'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'